### ISSUE TITLE
Edit repo name for spelling

### ISSUE THREAD

**Issue by morrowzl** [williamjones0706/Councious_Investing#19]
Does anyone object to changing the repository name to be "Conscious_Investing" (a spelling correction)? We will need to edit the repository utilized by the Heroku app, but that should be the only additional change required.

**Comment by rinatiwari** [comment]
William has to change it right?

**Comment by morrowzl** [comment]
Yeah, that's a good point. I'll assign the issue to him. Thanks!

**Comment by morrowzl** [comment]
Completed by Will just now!
